name: Pull Code, Run Tests, and Send Email

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:11

    steps:
      - name: Checkout Code and sing a donkey
        uses: actions/checkout@v3

      - name: Pull Code from Branch
        run: git pull origin main
        
      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven
          
      - name: Run TestNG tests on local machine and dance in rain
        run: |
          mvn clean compile test -Dtestng.xml=testng.xml

      - name: Get Job Status
        run: |
          job_status=$(mvn test -q -Dmaven.test.failure.ignore=true)
          if [ "$job_status" == "0" ]; then
            job_status="SUCCESS"
          else
            job_status="FAILURE"
          fi
